site_name: FrontTracker
theme:
  name: readthedocs
extra_css:
  - css/custom.css
nav:
  - Home: index.md
  - API:
      - Front: Front.md
      - FrontEllipse: FrontEllipse.md
      - FrontSkeleton: FrontSkeleton.md
      - FrontTracker: FrontTracker.md
      - Geometry: Geometry.md
  - Demos:
      - Getting Started: notebooks/getting_started.ipynb
      - Visualizing Labeled Fronts: notebooks/visualizing_labeled_fronts.ipynb
      - Front Orientation Analysis: notebooks/front_orientation_analysis.ipynb
      - Front Lifecycle Analysis: notebooks/front_lifecycle_analysis.ipynb
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_toc_entry: true
            heading_level: 2
            show_if_no_docstring: true
            show_docstring_description: true
            show_signature: true
            separate_signature: true
            docstring_section_style: table
            show_bases: true
            show_submodules: true
            show_inheritance_diagram: false
            show_private_members: true
            show_special_members: true
            filters: []
  - mkdocs-jupyter:
      execute: false